In [1]:
# coding:utf-8
%pylab inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import fetch_mldata
from chainer import cuda, Variable, FunctionSet,\
     optimizers,Chain,serializers
import chainer.functions  as F
import sys

import time
import datetime


import cv2

import os


#np.random.seed(0)

Populating the interactive namespace from numpy and matplotlib


In [29]:
def unko():
    try:
        A = range(4)
        a=[]
        i=0     
        while True:
            a.append(A[i])
            i+=1
    
    except IndexError as e:
        print("サイズがあってないで！！！")
        print("type:{0}".format(type(e)))
        print("args:{0}".format(e.args))
        print("message:{0}".format(e.message))
        print("{0}".format(e))
    

    except (TypeError) :
        print('ファイルが開けませんでした')

    except  :
        print('読み込み完了！！\n')

    finally:
        return a

b = unko()
print '続行！！'
print 'bの中身 : ',b




サイズがあってないで！！！
type:<type 'exceptions.IndexError'>
args:('list index out of range',)
message:list index out of range
list index out of range
続行！！
bの中身 :  [0, 1, 2, 3]


/Users/okuyamatakashi/.pyenv/versions/anaconda-4.0.0/envs/python2/lib/python2.7/site-packages/ipykernel/__main__.py:14: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6


In [57]:
print "------------varの実験----------"
var1 = 25
var2 = var1
var1 = 30
print "var1=",var1    # 30
print "var2=",var2 ,"\n"

print "------------listの実験----------"
list1 = [1, 2]
list2 = list1
list3 = [0]*len(list1)
list3[:]=list1[:]
list1.append(3)
print "list1=",list1
print "list2=",list2
print "list3=",list3,"\n"

print "------------arrayの実験----------"
array1 = np.array(np.arange(1,25).reshape(3,2,4))
array2 = array1
array1 +=5
print "array1=",array1,"\n"
print "array2=",array2,"\n"

array1 = np.array(np.arange(1,25).reshape(3,2,4))
array2 = np.zeros_like(array1)
array2[:]=array1[:]
array1 +=5
print "array1=",array1,"\n"
print "array2=",array2,"\n"

print "array1のshape=",array1.shape,"\n"
print "array2の=shape",array2.shape,"\n"

------------varの実験----------
var1= 30
var2= 25 

------------listの実験----------
list1= [1, 2, 3]
list2= [1, 2, 3]
list3= [1, 2] 

------------arrayの実験----------
array1= [[[ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]]

 [[22 23 24 25]
  [26 27 28 29]]] 

array2= [[[ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]]

 [[22 23 24 25]
  [26 27 28 29]]] 

array1= [[[ 6  7  8  9]
  [10 11 12 13]]

 [[14 15 16 17]
  [18 19 20 21]]

 [[22 23 24 25]
  [26 27 28 29]]] 

array2= [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]] 

array1のshape= (3, 2, 4) 

array2の=shape (3, 2, 4) 



In [70]:
print datetime.date.today()
print datetime.datetime.now()
print 'This is %s'%(str(time.clock()).replace('.','-',1))
print str(time.clock()).replace('.','-',1)
#print str(time.time())

2016-10-24
<type 'datetime.time'>
2016-10-24 14:32:15.142692
This is 4-061682
4-0618


In [111]:
#print os.getcwd()
#print os.path.dirname('/Users/okyamatakashi/PyworksShare')

name = 'wahaha'
if name not in os.listdir('../desktop/') :
    os.mkdir('../desktop/'+name)
img_list = os.listdir('./DataKeep/Picture/Before')
#print img_list
for img_name in (img_list): 
    if '.jpg' in img_name or '.jpeg' in img_name or '.png' in img_name:
        print img_name

Before1.jpeg
Before10.jpg
Before100.jpg
Before101.jpg
Before102.jpg
Before103.jpg
Before104.jpg
Before105.jpg
Before106.jpg
Before107.jpg
Before108.jpg
Before109.jpg
Before11.jpg
Before110.jpg
Before111.jpg
Before112.jpg
Before113.jpg
Before114.jpg
Before115.jpg
Before116.jpg
Before117.jpg
Before118.jpg
Before119.jpg
Before12.jpg
Before120.jpg
Before121.jpg
Before122.jpg
Before123.jpg
Before124.jpg
Before125.jpg
Before126.jpg
Before127.jpg
Before128.jpg
Before129.jpg
Before13.jpg
Before130.jpg
Before131.jpg
Before132.jpg
Before133.jpg
Before134.jpg
Before135.jpg
Before136.jpg
Before137.jpg
Before138.jpg
Before139.jpg
Before14.jpg
Before140.jpg
Before141.jpg
Before142.jpg
Before143.jpg
Before144.jpg
Before145.jpg
Before146.jpg
Before147.jpg
Before148.jpg
Before149.jpg
Before15.jpg
Before150.jpg
Before151.jpg
Before152.jpg
Before153.jpg
Before154.jpg
Before155.jpg
Before156.jpg
Before157.jpg
Before158.jpg
Before159.jpg
Before16.jpg
Before160.jpg
Before161.jpg
Before162.jpg
Before163.jpg


In [113]:
y = max(5,6)
print y

6


In [118]:
a = ['chinko','unko']
b = 'chink'
if b not in a:
    a.append(b)
print a

['chinko', 'unko', 'chink']


In [11]:
import pickle
#fo = open(f, 'rb')
#d = cPickle.load(fo)
#fo.close()

a = ((np.arange(24)+1).reshape(2,4,3))

filename = 'unko.dump'
Hozondir = 'chinko'
if Hozondir not in os.listdir('./DataKeep/') :
    os.mkdir('./DataKeep/'+Hozondir)

fo = open('./DataKeep/'+Hozondir+'/'+filename,'w')

pickle.dump(a, fo)

fo.flush()
fo.close()



In [13]:
fo = open('./DataKeep/'+Hozondir+'/'+filename,'r')
# ファイルオブジェクトに対してload()を使う
b = pickle.load(fo)
print b

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [27]:
import random
list_a = ["aaa","bbb","ccc"]
x = list_a.index("aaa")
print x

img_list = os.listdir('./DataKeep/Picture/NotFat/')
print img_list[0:10]
random.shuffle(img_list)
print img_list[0:10]

0
['NotFat1.jpg', 'NotFat10.jpg', 'NotFat102.jpg', 'NotFat104.jpg', 'NotFat107.jpg', 'NotFat11.jpg', 'NotFat112.jpg', 'NotFat114.jpg', 'NotFat115.jpg', 'NotFat119.jpg']
['NotFat268.jpg', 'NotFat213.jpg', 'NotFat40.jpg', 'NotFat52.JPG', 'NotFat325.jpg', 'NotFat160.jpg', 'NotFat4.jpg', 'NotFat151.jpg', 'NotFat60.jpg', 'NotFat345.jpg']


In [5]:
#inputは数字のみ
n = input(u'数字を入力\n0->フォルダを指定\n1->コードの中のフォルダを使う\n>>>')
#raw_inputはなんでもありで文字型として受け取る
if n == 0:
    folder_list = raw_input(u'folder_list\n>>> ').split()
    print folder_list 

数字を入力
0->フォルダを指定
1->コードの中のフォルダを使う
>>>0
folder_list
>>> Charhan
['Charhan']


In [7]:
a = os.listdir('../imgNNdata')
print a

['dumpFatNotFatmizumasi77']
